name: quasi_flutter
description: "An opinionated set common configurations & tools for flutter projects."
version: 0.0.1
homepage: "https://github.com/Quasiflo/quasi-flutter"
publish_to: ""

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
